login page (also have some other changes -- see below)
jmoran-cei/TravelTrack-WebApp pull request #3
Opened 2022-07-19 19:49 UTC by jmoran-cei

- login page complete and styled
- implemented authService and authGuard
- added some content to home page
- added some pages (edit-profile, etc.) as placeholders for now

2022-07-21 12:35 UTC, swhook52 commented on src/app/home/home-page.component.css
> +.marg {
Make sure your class names reference the purpose of the element you're styling and not the styling it will apply.

2022-07-21 12:43 UTC, swhook52 commented on src/app/home/home-page.component.ts
> +  // FINISH YOUR BUCKET LIST: box 1 details
I think these box titles are stub data?

Maybe you'll be pulling this information from an API in the future? If so, you should make it look like you're doing that now by using a service that returns an `Observable<SomeType>`.

Maybe this is static text on the page. If so, your static text should try to stay in HTML as much as possible. This helps with translation tools and reduces clutter in the component.

2022-07-21 12:46 UTC, swhook52 commented on src/app/home/home-section1/home-section1.component.css
> +  @media (max-width: 1100px) {
all media queries should go at the bottom of the CSS file.

2022-07-21 13:15 UTC, swhook52 commented on src/app/travel-app.component.ts
> +  // router?:any
make sure you review each commit before committing for unused code and remove it.

2022-07-21 14:02 UTC, swhook52 commented on src/app/user/login/login.component.ts
> +  username:any
remove `any` references. Always try to find a type. Otherwise TypeScript serves no purpose.

2022-07-21 14:09 UTC, swhook52 commented on src/app/user/shared/authentication.service.ts
> +  public isLoggedIn$: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false)
happy to see a use of BehaviorSubject.

It's very rare to expose  a BehaviorSubject outside of the class. These are typically meant to control and create your own observables but you don't want the calling code calling `.next()` on it and controlling the observable in your service. 

Because of this, you can have a private behavior subject but then have a public observable that is the `_isLoggedIn$.asObservable()`. Now you have a readonly version of your observable for the calling code to use.

You'll also want to read up on `shareReplay` and `publishReplay` to better understand how you share an observable across many subscribers.

When you reference this observable, I noticed you're calling `GetValue()`. That's a BehaviorSubject` thing and it breaks the Observable process. you'll need to change all those locations that use `GetValue()` to actually be using observables. This might mean you need to do `async` pipes in the view. This might also mean you need to `Subscribe` (and unsubscribe). There are may team members that just went through this process that can help out if you get stuck.

2022-07-21 14:11 UTC, swhook52 commented on src/app/home/home-section1/home-section1.component.html
> +    <ng-container *ngIf="auth.isLoggedIn$.getValue()">
I talk about getValue a little later in the review, but you should not reference a service that is pulled in from your component like this. Your component should call the auth service and set a property in your component for the view to read. something like:

```
this.isLoggedIn = this.auth.isLoggedIn$.pipe(take(1));
```

then your view would do:
```
<ng-container *ngIf="isLoggedIn | async">
```

2022-07-21 14:12 UTC, swhook52 requested changes
Let's get some of this observable stuff taken care of and we'll review again. Reach out if you need help.

2022-07-22 13:07 UTC, jmoran-cei commented on src/app/user/shared/authentication.service.ts
(not referencing any code, just commenting an update)
My adjustments are added. I appreciate your in depth feedback! 

I spent a decent bit of time learning more rxjs stuff (observables, subjects, subject behavior, replays, some operators). I was able to learn enough to grasp more understanding and enough to be able to (hopefully successfully) improve my code from before and have it function how it should through better practice.

2022-07-22 13:07 UTC, jmoran-cei commented on src/app/user/shared/authentication.service.ts
@swhook52

2022-08-01 17:49 UTC, merged